
### register
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "sssss",
  "email": "user1@gmail.com",
  "password": "Rakib@123"
}

### login
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "superadmin@gmail.com",
  "password": "12345678"
}




### create category  
POST  http://localhost:8000/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzg2ODE5MDkxLCJleHAiOjE3ODY5MDU0OTF9.IY31HUjbOunuPqrQxCcfwNJz3BkhJqGj87tnBilNcZg

{
  "name": "Cleaning 2",
  "description": "This is the description of Cleaning plumbing.",
  "isActive": false
}
### get all category  
GET  http://localhost:8000/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzg2ODE5MDkxLCJleHAiOjE3ODY5MDU0OTF9.IY31HUjbOunuPqrQxCcfwNJz3BkhJqGj87tnBilNcZg

### update category  
PATCh  http://localhost:8000/api/category/21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzg2ODE5MDkxLCJleHAiOjE3ODY5MDU0OTF9.IY31HUjbOunuPqrQxCcfwNJz3BkhJqGj87tnBilNcZg

{
  "name": "Cleaning 2"
}


### update category  
GET    http://localhost:8000/api/category/21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzg2ODE5MDkxLCJleHAiOjE3ODY5MDU0OTF9.IY31HUjbOunuPqrQxCcfwNJz3BkhJqGj87tnBilNcZg

{
  "name": "Cleaning 2",
  "description": "Updated description for Cleaning 2",
  "isActive": true
}





